name: Mergebot

on:  
  workflow_run:
    workflows:
      - Pull request
    types:
      - completed
  workflow_dispatch:
jobs:
  auto-merge:
     name: Auto merge
     runs-on: ubuntu-latest
     timeout-minutes: 1
     steps:
       - name: Generate tokens
         id: generate_token     
         uses: tibdex/github-app-token@v1      
         with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
       - name: weldonesir
         env:
          github_token: ${{ steps.generate_token.outputs.token }}  
          run: echo "this is github app token  ${{ steps.generate_token.outputs.token }}"
         uses: e-conomic/mergebot@v1
         with:
          github_token:  ${{ steps.generate_token.outputs.token }}
          run: echo "Ubaid  ${{ steps.generate_token.outputs.token }}"
